name: CI - genesettools

on:
  push:
    paths:
      - 'genesettools/**'
  pull_request:
    paths:
      - 'genesettools/**'

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("remotes", "testthat", "readr", "httr"), repos="https://cloud.r-project.org")'
      - name: Run tests
        working-directory: ./genesettools
        run: |
          Rscript -e 'remotes::install_local(".", upgrade = "never", dependencies = FALSE)'
          Rscript -e 'library(testthat); testthat::test_dir("tests/testthat")'
